### PR TITLE
update wiggle to allow for multiple variables

### PR DESCRIPTION
**Pull request by alexWhitworth**
Updates the `wiggle` function, and provides associated tests, to allow for `wiggle` to be used with multiple variables instead of only a single variable. This is particularly useful in the case of repeated measures data with test and control groups.

eg. here we have a dataset with a treatment/control indicator `treat` and a repeated measures value `date`:

```
example_ob <- draw(data, "average")
wiggle(example_ob, varlist= c("treat", "date"), valueslist= list(c(0,1), c(1:10)))
```

### CODE REVIEW

**Comment by jknowles** [comment]
This looks solid @alexWhitworth -- can you make the documentation more clear as to whether the wiggle does all combinations of elements in the value list, or just independently wiggles each variable. I think if that is cleared up, this can get merged right in.

**Comment by alexWhitworth** [comment]
@jknowles I'm happy to update the documentation. I can't get to it tonight but perhaps tomorrow or Wednesday. 

To answer your question (which I don't think was really a question), wiggling is done recursively with the result being all combinations. IE. in the initial example, you would go from 1 observation to 20 (1 * 2 * 10).

**Comment by jknowles** [comment]
Great. Thanks @alexWhitworth -- when you do that also add yourself to the Description file as a "contributor" to get credit for your contribution in the package documentation :smile:

**Comment by alexWhitworth** [comment]
@jknowles documentation updated. Thanks for the `ctb` 👍

**Comment by carlbfrederick** [comment]
Sounds like a cool feature, thanks @alexWhitworth!  I'll let @jknowles merge the pull request.

**Comment by jknowles** [comment]
Great addition @alexWhitworth  -- it's always :heart: when someone contributes to your project. CRAN update TBD, but probably before June.

**Comment by alexWhitworth** [comment]
@jknowles @carlbfrederick Glad to hear positive feedback. The package was quite helpful in a recent analysis / writeup.... It's a shame it wasn't available in the winter of 2014 / spring 2015--probably would have saved substantial time on my MS thesis haha

**Pull request merged**
