### PR TITLE
Standardized names to close issue #4

### PR DESCRIPTION
**Pull request by carlbfrederick**
This series of commits of standardizes the names of function arguments and returned objects and updated Vignettes and Examples to make them work again.

Also it should pass the checks because I un-depended `plotREsim` on `dplyr`

With this we can close issue #4

### CODE REVIEW

**Comment by jknowles** [comment]
This is failing the unit tests for `groupSim` and for `expectedRank` (see Travis link above). I can go ahead and update those on my own if you like.

**Comment by carlbfrederick** [comment]
It doesn't matter to me ... I can fix them this afternoon.  I thought I was doing well by remembering the vignettes and examples :)

Let me know if you want me to do them

**Comment by jknowles** [comment]
Why don't you knock those out and I'll put the finishing touches on `shinyMer` which I now have working pretty well and am on a roll with!

**Comment by carlbfrederick** [comment]
will do

**Comment by carlbfrederick** [comment]
merging pull request and closing ... Now

**Comment by carlbfrederick** [comment]
now merged and closed

**Pull request merged**
